-- MySQL Script generated by MySQL Workbench
-- 08/10/16 21:21:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzytkownik` (
  `idklient` INT NOT NULL AUTO_INCREMENT,
  `haslo` VARCHAR(45) NULL,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tel` INT NULL,
  `pesel` VARCHAR(45) NULL,
  `rola` VARCHAR(45) NULL,
  PRIMARY KEY (`idklient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film` (
  `idfilm` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(45) NULL,
  `tytul_oryginal` VARCHAR(45) NULL,
  `premiera` VARCHAR(45) NULL,
  `wiek` INT NULL,
  `czas_trwania` VARCHAR(45) NULL,
  `produkcja` VARCHAR(45) NULL,
  `gatunek` VARCHAR(45) NULL,
  `wersja` VARCHAR(45) NULL,
  `od_lat` INT NULL,
  `opis` VARCHAR(45) NULL,
  `aktorzy` VARCHAR(45) NULL,
  PRIMARY KEY (`idfilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `idsala` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL,
  `ilosc_miejsc` INT NULL,
  `typ` VARCHAR(45) NULL,
  `liczba_rzedow` INT NULL,
  `liczba_miejsc` INT NULL,
  PRIMARY KEY (`idsala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seans` (
  `idseans` INT NOT NULL AUTO_INCREMENT,
  `idfilm` INT NOT NULL,
  `idsala` INT NOT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`idseans`),
  INDEX `fk_seans_film1_idx` (`idfilm` ASC),
  INDEX `fk_seans_sala1_idx` (`idsala` ASC),
  CONSTRAINT `fk_seans_film1`
    FOREIGN KEY (`idfilm`)
    REFERENCES `mydb`.`film` (`idfilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seans_sala1`
    FOREIGN KEY (`idsala`)
    REFERENCES `mydb`.`sala` (`idsala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bilet_rodzaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bilet_rodzaj` (
  `idbilet_rodzaj` INT NOT NULL,
  `rodzaj` VARCHAR(45) NULL,
  `cena` VARCHAR(45) NULL,
  `typ_filmu` VARCHAR(45) NULL,
  PRIMARY KEY (`idbilet_rodzaj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bilet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bilet` (
  `idbilet` INT NOT NULL,
  `idklient` INT NOT NULL,
  `idfilm` INT NOT NULL,
  `idbilet_rodzaj` INT NOT NULL,
  `idseans` INT NOT NULL,
  `stan` VARCHAR(45) NULL,
  `miejsce` VARCHAR(45) NULL,
  `cena` VARCHAR(45) NULL,
  `typ` VARCHAR(45) NULL,
  PRIMARY KEY (`idbilet`),
  INDEX `fk_bilet_klient_idx` (`idklient` ASC),
  INDEX `fk_bilet_film1_idx` (`idfilm` ASC),
  INDEX `fk_bilet_seans1_idx` (`idseans` ASC),
  INDEX `fk_bilet_bilet_rodzaj1_idx` (`idbilet_rodzaj` ASC),
  CONSTRAINT `fk_bilet_klient`
    FOREIGN KEY (`idklient`)
    REFERENCES `mydb`.`uzytkownik` (`idklient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilet_film1`
    FOREIGN KEY (`idfilm`)
    REFERENCES `mydb`.`film` (`idfilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilet_seans1`
    FOREIGN KEY (`idseans`)
    REFERENCES `mydb`.`seans` (`idseans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilet_bilet_rodzaj1`
    FOREIGN KEY (`idbilet_rodzaj`)
    REFERENCES `mydb`.`bilet_rodzaj` (`idbilet_rodzaj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
