package org.zut.pbai.model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BiletRodzaj generated by hbm2java
 */
@Entity
@Table(name = "bilet_rodzaj", catalog = "mydb")
public class BiletRodzaj implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idbiletRodzaj;
	private String rodzaj;
	private String cena;
	private String typFilmu;
	private Set<Bilet> bilets = new HashSet<Bilet>(0);

	public BiletRodzaj() {
	}

	public BiletRodzaj(int idbiletRodzaj) {
		this.idbiletRodzaj = idbiletRodzaj;
	}

	public BiletRodzaj(int idbiletRodzaj, String rodzaj, String cena, String typFilmu, Set<Bilet> bilets) {
		this.idbiletRodzaj = idbiletRodzaj;
		this.rodzaj = rodzaj;
		this.cena = cena;
		this.typFilmu = typFilmu;
		this.bilets = bilets;
	}

	@Id

	@Column(name = "idbilet_rodzaj", unique = true, nullable = false)
	public int getIdbiletRodzaj() {
		return this.idbiletRodzaj;
	}

	public void setIdbiletRodzaj(int idbiletRodzaj) {
		this.idbiletRodzaj = idbiletRodzaj;
	}

	@Column(name = "rodzaj", length = 45)
	public String getRodzaj() {
		return this.rodzaj;
	}

	public void setRodzaj(String rodzaj) {
		this.rodzaj = rodzaj;
	}

	@Column(name = "cena", length = 45)
	public String getCena() {
		return this.cena;
	}

	public void setCena(String cena) {
		this.cena = cena;
	}

	@Column(name = "typ_filmu", length = 45)
	public String getTypFilmu() {
		return this.typFilmu;
	}

	public void setTypFilmu(String typFilmu) {
		this.typFilmu = typFilmu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "biletRodzaj")
	public Set<Bilet> getBilets() {
		return this.bilets;
	}

	public void setBilets(Set<Bilet> bilets) {
		this.bilets = bilets;
	}

}
