package org.zut.pbai.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name = "sala", catalog = "pbai2016db")
public class Sala implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idsala;
	private String nazwa;
	private Integer iloscMiejsc;
	private String typ;
	private Integer liczbaRzedow;
	private Integer liczbaKolumn;
	private Set<Seans> seanses = new HashSet<Seans>(0);

	public Sala() {
	}

	public Sala(String nazwa, Integer iloscMiejsc, String typ, Integer liczbaRzedow, Integer liczbaKolumn,
			Set<Seans> seanses) {
		this.nazwa = nazwa;
		this.iloscMiejsc = iloscMiejsc;
		this.typ = typ;
		this.liczbaRzedow = liczbaRzedow;
		this.liczbaKolumn = liczbaKolumn;
		this.seanses = seanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsala", unique = true, nullable = false)
	public Integer getIdsala() {
		return this.idsala;
	}

	public void setIdsala(Integer idsala) {
		this.idsala = idsala;
	}

	@Column(name = "nazwa", length = 45)
	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	@Column(name = "ilosc_miejsc")
	public Integer getIloscMiejsc() {
		return this.iloscMiejsc;
	}

	public void setIloscMiejsc(Integer iloscMiejsc) {
		this.iloscMiejsc = iloscMiejsc;
	}

	@Column(name = "typ", length = 45)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Column(name = "liczba_rzedow")
	public Integer getLiczbaRzedow() {
		return this.liczbaRzedow;
	}

	public void setLiczbaRzedow(Integer liczbaRzedow) {
		this.liczbaRzedow = liczbaRzedow;
	}

	@Column(name = "liczba_kolumn")
	public Integer getLiczbaKolumn() {
		return this.liczbaKolumn;
	}

	public void setLiczbaKolumn(Integer liczbaKolumn) {
		this.liczbaKolumn = liczbaKolumn;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "sala")
	public Set<Seans> getSeanses() {
		return this.seanses;
	}

	public void setSeanses(Set<Seans> seanses) {
		this.seanses = seanses;
	}

}
