package org.zut.pbai.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seans generated by hbm2java
 */
@Entity
@Table(name = "seans", catalog = "mydb")
public class Seans implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idseans;
	private Film film;
	private Sala sala;
	private Date data;
	private Set<Bilet> bilets = new HashSet<Bilet>(0);

	public Seans() {
	}

	public Seans(Film film, Sala sala) {
		this.film = film;
		this.sala = sala;
	}

	public Seans(Film film, Sala sala, Date data, Set<Bilet> bilets) {
		this.film = film;
		this.sala = sala;
		this.data = data;
		this.bilets = bilets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idseans", unique = true, nullable = false)
	public Integer getIdseans() {
		return this.idseans;
	}

	public void setIdseans(Integer idseans) {
		this.idseans = idseans;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfilm", nullable = false)
	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsala", nullable = false)
	public Sala getSala() {
		return this.sala;
	}

	public void setSala(Sala sala) {
		this.sala = sala;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", length = 19)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seans")
	public Set<Bilet> getBilets() {
		return this.bilets;
	}

	public void setBilets(Set<Bilet> bilets) {
		this.bilets = bilets;
	}

}
